### ISSUE TITLE
More details on the hardware workmanship

### ISSUE THREAD

**Issue by smichaelsen** [TheNitek/RfidShelf#1]
A little more detail on how you assemble and treat the hardware would be helpful for someone like me who has close to zero experience crafting physical things.

What tools do you use? (soldering iron?, saw?, wire stripper?, ...)
Can you provide a picture of the hardware fitted inside the shelf? How did you cut out the needed space?

**Comment by TheNitek** [comment]
Should have added TODO notes for these sections 😀 I will add these infos step by step. Still have to take a few pictures and figure out how to draw a nice wiring picture.
