### ISSUE TITLE
How to set up and run the firmware

### ISSUE THREAD

**Issue by smichaelsen** [TheNitek/RfidShelf#12]
Please bear with me, this really is my first micro electronics project.

I used the [nodemcu-flasher](https://github.com/nodemcu/nodemcu-flasher) to flash the firmware from this repo onto my NodeMCU (well there was no error and a blue LED was flashing, so I suppose it worked). But I don't know how to proceed. How do I start the firmware? Do I need additional software like ESPlorer? A few examples I found were related to the Arduino which is not applicable here I guess.

I can read docs or tutorials but I need a pointer into the right direction.

**Comment by TheNitek** [comment]
Well there is some documentation missing on this topic ;-) Just created #13 as a reminder.

Use some kind of serial terminal software (like putty or arduino IDE) to connect to the devices serial port and watch the output for error messages. If there are none, you should be able to see a new wifi network named "RfidShelf" (Password "lacklack"). If you join the Wifi you will get a setup page to connect to your own wifi. Once this is done you can access the admin page via your wifi. There you can upload music or start the card pairing.
