### ISSUE TITLE
Support for 125 kHz Reader EM4100

### ISSUE THREAD

**Issue by hankman13** [TheNitek/RfidShelf#17]
Hi,
do you think that it's possible to add support for the 125 kHz Reader (EM4100/RDM6300/RDM630) [AliExpress](https://de.aliexpress.com/item/Free-shipping-UART-125Khz-EM4100-RFID-Card-Key-ID-Reader-Module-RDM6300-RDM630-For-Arduino/32279622758.html?spm=a2g0x.search0104.3.1.77cb3719KzeZlj&ws_ab_test=searchweb0_0,searchweb201602_5_10320_10065_10068_318_10547_319_10546_317_10548_10696_450_10084_10083_10618_452_535_534_10304_533_10307_10820_532_204_10843_10059_10884_10887_100031_320_10103_448_449,searchweb201603_60,ppcSwitch_0&algo_expid=7ae266ba-59ad-488b-935f-e58f10581791-0&algo_pvid=7ae266ba-59ad-488b-935f-e58f10581791&transAbTest=ae803_4)
I own this device and i would like to use these cards, because I'm already using a RFID Jukebox from this project: [RPi-Jukebox-RFID](https://github.com/MiczFlor/RPi-Jukebox-RFID)
I think your solution will be more friendly for power consumption.
Thanks!

One more thing, could you please add a picture of you Webinterface? I'm still collecting and waiting for my chinabag for building the RFID Shelf.

**Comment by TheNitek** [comment]
Sorry for the late feedback. I guess 125kHz support should be possible, but nothing this project supports right now. Feel free to create a pull request.

I'll add a picture soon, right now it is just the main area I am working on and I didn't won't to have to update the screenshot everytime I change something (or have an outdated screenshot).
