### ISSUE TITLE
Increase Upload Speed

### ISSUE THREAD

**Issue by TheNitek** [TheNitek/RfidShelf#21]
Currently the upload speed is around 100kb/s do bigger files take ages. A increase in upload speed would be nice. Ideas are welcome ;-)

**Comment by TheNitek** [comment]
Tried my best, but the ESP8266 doesn't seem to offer a better speed for HTTP Uploads ...

**Comment by TheNitek** [comment]
FTP upload might be an option. Seems to increase the upload speed compared to http

**Comment by leachiM2k** [comment]
Did you try the upload with ESPAsyncWebServer?

**Comment by TheNitek** [comment]
I've been thinking about this for a while now, but the AsyncWebServer is a dangerous step regarding race conditions and would need some major rework on the web control code

**Comment by leachiM2k** [comment]
I tried it here: https://github.com/leachiM2k/RfidShelf/tree/feature/async-webserver 
and so far it compiles. But I have to test it on the device itself.
It was not as much work as I thought.

**Comment by TheNitek** [comment]
Making it compile isn't what worries me, but making it run stable. I expect a major refactoring of the web handlers to be necessary to prevent race conditions.

**Comment by TheNitek** [comment]
Using ESPAsyncWebServer seems to even reduce the throughput to around 70kb/s - That's unexpected ands disappointing

**Comment by mkuger** [comment]
Assuming sound quality is not that of an issue: try and reduce bitrate in browser before uploading?
