### ISSUE TITLE
Hardware Button support

### ISSUE THREAD

**Issue by Tedious01** [TheNitek/RfidShelf#25]
Hi,
really nice project, I thing I'd like to build it. Just one question - AFAIK there are software buttons in web server. Would it be possible to implement hardware button support (Play/Pause, Vol up, Vol down)? Or is this already implemented and I didn't find it. Would be great if the childs would be able to pause etc. just by a button...
Best regards from Hessen,

Sascha

**Comment by TheNitek** [comment]
There is (well hidden) short discussion about hardware buttons here: #11
In short: Not supported right now and there is only a limited number of PINs left to use. Also @BeAr1987 has a fork which supports volume control.

**Comment by Tedious01** [comment]
Thanks for your feedback, I'll have a look it.

**Comment by TheNitek** [comment]
After a little bit of thinking:
Volume is not a problem using the analog in
Maybe GPIO01 and 03 (RX/TX for the serial connection) can be used for additional buttons - if wired correctly, even the USB flashing should still continue to work (although serial debugging won't be possible anymore)

**Comment by TheNitek** [comment]
You can now set BUTTONS_ENABLE in ShelfConfig.h to use TX for pause/resume, RX for skip track and A0 for volume control.
