### ISSUE TITLE
VS1053 initializes sporadically

### ISSUE THREAD

**Issue by SiJoNi** [TheNitek/RfidShelf#26]
This is my first project with microcontrollers so far and i am facing a little issue.
It seems that my setup only starts in about half of the cases. When it is not working it fails at initializing the music player. (!_musicPlayer.begin()) I have to switch power off completey and then repower it to try again. If I get past this point everything is working as expected. Did you had similiar issues?

Thanks a lot for sharing this cool project. I hope my son will have as much fun as I have with it.

**Comment by TheNitek** [comment]
What setup are you running? The red VS1053 board? Did you wire it using jumper wires? How long are the wires? Did you check each of them? My guess would be the wiring. Of all the stupid things that happend during the development, I never had any issues like that with the VS1053.

**Comment by SiJoNi** [comment]
I am running the setup with the Adafruit Music Maker FeatherWing. Yes it is wired with jumper cables (10 cm). I will exchange all of them to see if I can fix it this way. Thanks for the quick help.

**Comment by SiJoNi** [comment]
After resoldering the VS1053 and replacing every jumper wire it finally works. Thanks a lot and keep up the good work.

**Comment by TheNitek** [comment]
Nice, thanks for the feedback! I'd be happy to see some pictures once you finished your build ;-)
