### ISSUE TITLE
Port to ESP32

### ISSUE THREAD

**Issue by TheNitek** [TheNitek/RfidShelf#30]
ESP32 would allow the use of Bluetooth and probably remove the need for the VS1053 while adding more pins, performance and other nice features. The price hase went down by now, so it looks like a nice step forward.

Think about:
* Can the ESP8266 still be supported?
* Which ESP32? Maybe the AI Thinker Audio Board?

Any thoughts?

**Comment by warhog** [comment]
I also thought about using the ESP32 (funny note, it was yesterday evening while showing the radio to a friend :) ). It shouldn't be an issue to have support for ESP8266, I did this in a project already and with some preprocessor ifdefs this can be done. The libs are almost the same.

Pinwise its a good idea, I've built a portable variant (description to follow) using LiIons and have not enough pins left for features like battery management and state feedback, ...

I dunno the complexity of playing music files on the ESP directly but quick googling showed up ESP8266Audio (works for ESP32 also) lib that can do the job. Might be an idea to reduce hardware complexity a bit and give additional features. Maybe some research is needed on quality (both of my VS1053  are quite noisy).

While the AI Thinker Audio Board is quite nice it lacks IOs (e.g. ADC1) for my use case. With careful planning we might be (almost) independent of the used board (but with increased complexity).

It think all in all it is also a question of the projects direction and the target audience. New boards introduce complexity both on HW and SW level. At least from my side I'm short on time always (second child, parental time is sadly over now).
As a conclusion I really like the idea but I think an analysis with pros and cons is needed.


Or we just give it a try, maybe it is so great that we drop ESP8266 support :D

**Comment by TheNitek** [comment]
Well I don't think using ifdefs will work too well, because there will be too many differences (audio output, SD access ...). Branching seems to more reasonable i guess.

The AI Thinker Board has a BAT-Port included and I like how it already brings an SD-slot and the amp. Unfortunately it doesn't look like it provides SPI for the Rfid reader, so it's probably not any option anyway.
Main objective of this project is and should be to be simple, so the ESP32 solution shouldn't become any more complex than the current one - Simplification would be very welcome (that's why the AI Thinker board is so appealing).
I'd love to support web radio (using an ESP32 with PSRAM) und Bluetooth Audio. Also using a I2S amp seems good for sound quality.


If you have noise on your VS1053 it's probably the SPI wiring. Only way for me to get rid of this was use my PCB. That solved any noise issues.
BTW I'd love to see what you made out of this project, so if you have more to share I'd be more than interested ;-)

**Comment by torwag** [comment]
Being new to this, I was wondering, the switch to an ESP32 board would also solve #25, as the limitation of GPIOs seems to be the challenge here. Furthermore, more GPIOs would enable battery charging, LEDs and other additional features in the future. As for replacing the VS1053 with ESP software, I guess it would only make sense, if the software solutions shows great benefits over the dedicated chip solution. Usually, that is quite a bit of work and bug-prone as well, thus, a dedicated chip might be complex on the soldering side, but easier on the software stack side.
I am looking into a (possible portable) device which I can easily configure via the webinterface, including adding new cards and files, but which can be controlled by the kids with the usual three button control (play/pause, vol+/skip and vol-/rev).

**Comment by warhog** [comment]
I've just gave it a quick try using an ESP32 dev board and Adafruit UDA1334A I2S breakout using this code https://github.com/schreibfaul1/ESP32-audioI2S. I have not tested SD yet but streaming is working.
Using my headphones the audio quality of the tested webstreams was stunning.
Regarding the pins it improves the situation (about 10 pins are free when using SD card).
Hardware complexity is almost equal: ESP32 board, I2S board, SD board and amplifier board(s).
I'm a bit short on time due to kids and heavy workload in the company but I'll try to continue playing with it for eval purposes.

**Comment by TheNitek** [comment]
I did nearly the same using https://www.aliexpress.com/item/Max98357-I2S-3W-Class-D-Amplifier-Breakout-Interface-Dac-Decoder-Module-Filterless-Audio-Board-For-Raspberry/33004419753.html?spm=a2g0s.9042311.0.0.27424c4dHdk7ZE (so no need a additional amplifier board) and I was also very pleased.
I was thinking about the ESPs SD controller, but it seams that SPI-SD-readers are cheaper than SD slots with additional electronics.
Additional pins would also allow for the RFID reader to use interrupts.

All in all I am quite tempted but I fear that I also might not have enough free time to get this done right now.

**Comment by TheNitek** [comment]
Out of scope for now
