### ISSUE TITLE
Add Alexa Support

### ISSUE THREAD

**Issue by TheNitek** [TheNitek/RfidShelf#48]
Make "play" and "pause" (and maybe night mode/volume) work through Alexa

**Comment by leachiM2k** [comment]
Great idea. I’ve already implemented this feature in a Raspberry version of TonUINO. I used MQTT for communication as it works very well with firewalls and different WiFi installations.
Do you have ideas about the implementation?

The main problem is the song name recognition. Therefore I used only numbers as folder names.

**Comment by TheNitek** [comment]
I'd go with a simple on/off using https://github.com/igorantolic/esp32-alexa-wemo-emulator Anything more seems to be beyond the scope if this project.

**Comment by TheNitek** [comment]
Implemented
