### ISSUE TITLE
PlatformIO won't compile Code

### ISSUE THREAD

**Issue by Clautens** [TheNitek/RfidShelf#51]
Hi!
really nice projxct. I build a version of RfidShelf for my son some years ago. Now I need a second one for my daughter!
I downloaded your project and opened the "RfidShelf" folder in PlatformIO.
I'm using an ESP8266 Lolin-Board with an Adafruit FeatherWing. If I hit the Build-Button the following error occurs, followed by some other errors which I think they are all related to the first one:

```
.pio\libdeps\nodemcuv2\SD/utility/Sd2PinMap.h:371:2: error: #error Architecture or board not supported.
 #error Architecture or board not supported.
  ^
```
The Dependency Graph shows the following:

```
|-- <Adafruit VS1053 Library> 1.2.0
|   |-- <SD> 0.0.0-alpha+sha.041f788250
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <BoolArray> 0.2.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <EasyButton> 2.0.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266HTTPClient> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266httpUpdate> 1.3
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266HTTPClient> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <ESP8266SdFat> 1.1.0
|   |-- <SPI> 1.0
|-- <MFRC522> 1.4.6
|   |-- <SPI> 1.0
|-- <SPI> 1.0
|-- <WifiManager> 0.15.0
|   |-- <DNSServer> 1.1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <Espalexa> 0.0.0-alpha+sha.09981160b5
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <SD> 0.0.0-alpha+sha.041f788250
|   |-- <SPI> 1.0
```

Could you please give me a hint what I'm doing wrong?
Thank you!

**Comment by TheNitek** [comment]
Best guess: Platformio just released there new 5.0 core which changed the dependency resultion. I guess that might lead to the wrong SD library being included. I‘ll have closer look tomorrow.

**Comment by TheNitek** [comment]
I fixed the SD dependency, so it should compile now. Thanks for reporting this!

**Comment by Clautens** [comment]
Works like a charm! thank you very much!
